kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  namespace: botnext
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: botnext.volume.test
  namespace: botnext
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  hostPath:
    path: /home/kuber/Botnext/BotnextUploadImages

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: botnext.claim.test
  namespace: botnext
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
