apiVersion: ceph.rook.io/v1beta1
kind: Filesystem
metadata:
  name: testfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 3
  metadataServer:
    activeCount: 1
    activeStandby: true